### ISSUE TITLE
Embedded Zookeeper is not reachable outside the container

### ISSUE THREAD

**Issue by mathiasdan** [docker-solr/docker-solr#291] opened 2020-02-16 18:53 UTC
I am running Solr in cloud mode with embedded zookeeper : 
```docker run -d -p 9983:9983 -p 8983:8983 solr:7.5 -f -cloud```
I can reach the Admin UI on 8983,but I can't access the embedded Zookeeper on port 9983!

Is there an easy way to do this?

**Comment by dsmiley** [comment] 2020-02-25 18:41
I can't reproduce this.  I ran this as well and found that port 9983 was open, tested with Mac's Network Utility port scanner.
`docker run --rm -p 9983:9983 -p 8983:8983 --name solr solr:7.5 -cloud`

**Comment by mathiasdan** [comment] 2020-02-25 20:37
I think everything is fine as long as your container host is `127.0.0.1/localhost`. I have just tried on linux and everything went fine! 
On Docker Toolbox for Windows, the container host is `192.168.99.100`. If I try to reach solr admin UI on `192.168.99.100:8983`, it works. However I can't reach embedded zookeeper on `192.168.99.100:9983`

**Comment by janhoy** [comment] 2020-02-26 12:05
I'm quite sure that Zookeeper binds to all interfaces by default. See https://issues.apache.org/jira/browse/SOLR-14118 which will change this for 9.0 to bind to 127.0.0.1 only for security reasons.

**Comment by janhoy** [comment] 2020-03-27 08:40
Closing as cannot-reproduce.

**Closed by janhoy** 2020-03-27 08:40 UTC
Labels: cannot-reproduce

**Comment by pankajxyz** [comment] 2021-04-19 03:58
> I am running Solr in cloud mode with embedded zookeeper :
> `docker run -d -p 9983:9983 -p 8983:8983 solr:7.5 -f -cloud`
> I can reach the Admin UI on 8983,but I can't access the embedded Zookeeper on port 9983!
> 
> Is there an easy way to do this?

I also ran into the same problem. What's the fix?
