### ISSUE TITLE
solr docker image starts with warning logs

### ISSUE THREAD

**Issue by farajn9** [docker-solr/docker-solr#343] opened 2020-09-02 08:17 UTC
When trying to start solr image by running
`docker run -p 8983:8983 -t solr`

Getting this warning in the beginning
```
The currently defined JAVA_HOME (/usr/local/openjdk-11) refers to a location
where java was found but jstack was not found. Continuing.
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
2020-09-02 08:14:10.743 INFO  (main) [   ] o.e.j.u.log Logging initialized @819ms to org.eclipse.jetty.util.log.Slf4jLog
2020-09-02 08:14:10.800 WARN  (main) [   ] o.e.j.x.XmlConfiguration Ignored arg: <Arg name="threadpool">
    <New id="threadpool" class="com.codahale.metrics.jetty9.InstrumentedQueuedThreadPool"><Arg name="registry">
        <Call id="solrJettyMetricRegistry" name="getOrCreate" class="com.codahale.metrics.SharedMetricRegistries"><Arg>solr.jetty</Arg></Call>
      </Arg></New>
  </Arg>
```

Is it expected?

**Comment by bradjones1** [comment] 2020-09-23 22:08
Duplicate of #273

**Comment by dsmiley** [comment] 2020-09-24 03:23
Yeah; report issues upstream to Solr that aren't docker-solr specific.  The jstack one is kinda related but not since bin/solr could be improved to support "jattach" if it's on the path.  CC @janhoy on that.
Closing.

**Closed by dsmiley** 2020-09-24 03:23 UTC
