### ISSUE TITLE
Start problem in kubernetes

### ISSUE THREAD

**Issue by xrow** [docker-solr/docker-solr#6] opened 2016-01-04 13:47 UTC
Hi,

I have noticed that you can`t start the docker image in kubernetes, because kubernetes will set the following env vars:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=solr-rrdd1
SOLR_PORT_8983_TCP_PROTO=tcp
SOLR_PORT_8983_TCP=tcp://10.254.219.195:8983
SOLR_SERVICE_HOST=10.254.219.195
SOLR_SERVICE_PORT_SOLR=8983
SOLR_PORT=tcp://10.254.219.195:8983
SOLR_PORT_8983_TCP_ADDR=10.254.219.195
SOLR_PORT_8983_TCP_PORT=8983
SOLR_SERVICE_PORT=8983
SOLR_USER=solr
SOLR_UID=8983
SOLR_KEY=25C13C58807E90004AB8597AE48025ED13E57FFC
SOLR_VERSION=5.4.0
SOLR_SHA256=84c0f04a23047946f54618a092d4510d88d7205a756b948208de9e5afb42f7cd
```

The /opt/solr/bin/solr bin will act on SOLR_PORT set by kubernetes and will crash since it will have the value tcp://10.254.219.195:8983. I sugest using the var SOLR_SERVICE_PORT_SOLR, if var is set.

Else you have to change the name of your server in kubernetes from solr to solr2 for example.

**Comment by xrow** [comment] 2016-01-04 13:49
Another workaround is to set a var SOLR_PORT and overwrite the value.
   
 - name: "SOLR_PORT"
   value: "8983"

**Comment by makuk66** [comment] 2016-01-06 20:24
From https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md#environment-variables it sounds like that is expected behaviour on the kubernetes side.

Your workaround sounds straightforward, and it seems that if you want it you can constitute the original value from SOLR_PORT_8983_TCP_ADDR and SOLR_PORT_8983_TCP_PORT if you were to need it.

It'd be nice if we could avoid this pitfall. I can think of a few approaches to avoid this:
- document your overwrite workaround in the https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md as part of a "how to run docker-solr in kubernetes" entry
- use a wrapper to call the solr start script, and unset SOLR_PORT explicitly. But so far we've avoided the need for a wrapper
- configure the `SOLR_PORT` in `/opt/solr/bin/solr.in.sh` to explicitly set SOLR_PORT. We can do that from the Dockerfile easily, and I can't think of a disadvantage to that approach.

**Comment by xrow** [comment] 2016-01-07 08:26
I am thinking more about it. I would favor the wrapper, but i do not know how to properly add it to CMD. 

```
if [ -n "${SOLR_PORT}" && -z "$SOLR_SERVICE_PORT_SOLR" ]; then
    SOLR_PORT=$SOLR_SERVICE_PORT_SOLR
fi
```

What is your favorite choise?

**Comment by makuk66** [comment] 2016-01-07 11:08
I've made this change https://github.com/docker-solr/docker-solr/commit/949d6bece4e2ae1189d84210ae0b54b7ba87a37c.
Please can you build a local image with that change and confirm that it avoids this problem?

**Comment by xrow** [comment] 2016-01-07 14:34
To let you know your fix worked. Thanks a lot. You can update now the offical image.

https://hub.docker.com/r/xrowgmbh/solr/~/dockerfile/

**Comment by makuk66** [comment] 2016-01-07 15:28
Great, thanks for letting me know.
A new version of Solr is expected soonish, so we'll pick up this change when we update the official image for that.

**Comment by makuk66** [comment] 2016-01-20 15:01
The next version of Solr is still expected soonish :-)

Closing this because there's nothing left to do.

**Closed by makuk66** 2016-01-20 15:01 UTC
