### ISSUE TITLE
Plans to support solr 4.x?

### ISSUE THREAD

**Issue by derTobsch** [docker-solr/docker-solr#168] opened 2018-02-28 16:11 UTC
We have a old content media system that needs a solr 4.3 and I would like to start this solr instance in a docker container for development purposes. Do you plan to provide a solr 4.3 docker image? :)

It would be nice to get any feedback from you. Thanks!

**Comment by dsmiley** [comment] 2018-02-28 18:49
Duplicate of: https://github.com/docker-solr/docker-solr/issues/134  Please respond there.

**Closed** 2018-03-30 21:57 UTC
