### ISSUE TITLE
Not a valid Unicode code point: 0xFFFFFFFF  

### ISSUE THREAD

**Issue by sharif2008** [docker-solr/docker-solr#299] opened 2020-03-30 20:15 UTC
I am using solr8 in docker. Though it may be solr related issue I am posting it here as I am using solr in docker . I am continuously getting this issue. And most of time container/solr is stopped.  

```
[2020-03-30 20:09:23.675 ERROR (qtp1389774257-17) [   x:cricket] o.a.s.s.HttpSolrCall null:org.apache.velocity.exception.MethodInvocationException: Invocation of method 'toChars' in  class java.lang.Class threw exception java.lang.IllegalArgumentException: Not a valid Unicode code point: 0xFFFFFFFF at custom.vm[line 1, column 314]
        at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:280)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:212)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:304)
        at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:605)
        at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:72)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:158)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:304)
        at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:411)
        at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:144)
        at org.apache.velocity.runtime.directive.Foreach.renderBlock(Foreach.java:289)
        at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:259)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:295)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:377)
        at org.apache.velocity.Template.merge(Template.java:359)
        at org.apache.velocity.Template.merge(Template.java:264)
        at org.apache.solr.response.VelocityResponseWriter.write(VelocityResponseWriter.java:166)
        at org.apache.solr.response.QueryResponseWriterUtil.writeQueryResponse(QueryResponseWriterUtil.java:65)
        at org.apache.solr.servlet.HttpSolrCall.writeResponse(HttpSolrCall.java:873)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:582)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:423)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:350)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:505)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Not a valid Unicode code point: 0xFFFFFFFF
        at java.base/java.lang.Character.toChars(Character.java:8573)
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:506)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:494)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:198)
        ... 53 more
](url)
```

**Comment by janhoy** [comment] 2020-03-30 20:32
I see you use Velocity Response writer. Please share more about what Velocty template you are using and custom Velocity config. If you share step-by step how to reproduce from the `docker run` command and what other commands you have to run in order to trigger the exception.

**Comment by sharif2008** [comment] 2020-03-30 20:38
Thanks for your quick response. I have used default Velocty template . Basically all setting are default as they are in docker solr. If you don't mind, please my image from here 

> docker pull codebazz/kotha_solr8:2.0.0.1

Where you will my existing cores also.

**Comment by janhoy** [comment] 2020-03-31 18:52
I’m asking for a step by step reproduction, e.g.

    docker run -ti —rm -p 8983:8983 solr:8.5 bash
    solr -e techproducts 
    curl http://localhost:8983/solr/mycoll/browse?q=hello

**Comment by dsmiley** [comment] 2020-04-03 14:09
I don't think we should support Solr on docker-solr issues.  We should only support docker-solr here.

**Comment by janhoy** [comment] 2020-04-03 15:05
I agree that this looks like a pure Solr configuration or usage issue, so I'm closing this issue and asking you to ask your question on the solr-user mailing list: https://lucene.apache.org/solr/community.html#mailing-lists-irc 
When you do, please include a clear step by step reproduction guide, without requiring custom config or templates.

**Closed by janhoy** 2020-04-03 15:05 UTC

**Comment by sharif2008** [comment] 2020-05-10 17:42
> I don't think we should support Solr on docker-solr issues. We should only support docker-solr here.

Don't get me wrong. It is a docker-solr issue. And it is solved. I assume that there were some anonymous and non-authorized access in port 8983. So after blocking the port, everything is working fine. 

Sorry for the inconveniences . thanks

**Comment by jigangjin** [comment] 2020-06-03 05:58
Hi Sharif2008, could you elaborate more on how you solved this problem?  I am encountering the same problem as well.
