### ISSUE TITLE
ZooKeeper 3.5 connection problems with docker-compose example

### ISSUE THREAD

**Issue by daseinkapital** [docker-solr/docker-solr#230] opened 2019-07-11 21:19 UTC
While trying to build the containers provided with docker-compose, our team experienced issues on multiple computers with an error that we could not start solr and the individual containers could not connect to ZooKeeper.

Of note: we're using Windows 10, tried building both Solr 7 and Solr 7.7, and we are using Linux containers for Windows.

An image of the error can be found [here](https://i.imgur.com/Gm626kt.png), [here](https://imgur.com/5f38qcT), and [here](https://imgur.com/xFuNE0F).

**Comment by makuk66** [comment] 2019-07-16 18:21
It's hard to say from that what might be the cause. Did you figure it out?

**Comment by oldmanoldson** [comment] 2019-07-30 13:57
Why was this closed?  It still doesn't work...

**Comment by makuk66** [comment] 2019-07-30 14:57
There was not sufficient information there to reproduce or determine the cause. I asked for more info 2 weeks ago and didn't get any from the OP. I have a hard time image it being something specific to the solr image rather than a generic local docker config. So it's not actionable, and that's why I closed it. @oldmanoldson are you seeing a similar issue? Can you fill in some more details? What specific commands did you use, can you share your config, what have you tried to investigate it, etc.

**Comment by oldmanoldson** [comment] 2019-07-30 15:01
I'm getting the same exact errors as they are above.  The only commands I ran were `docker-compose build` and `docker-compose run`.  Since this is supposed to emulate solr cloud is this expecting to be in a docker swarm?

**Comment by makuk66** [comment] 2019-07-30 15:57
What's in your `docker-compose.yml`? What is supposed to emulate solr cloud?

**Comment by oldmanoldson** [comment] 2019-07-30 16:00
I just took your `docker-compose.yml`, only thing that was changed was the version of solr and that was only after I received the above error.  Isn't this Docker Container supposed to emulate/be a solr cloud environment?  Or do I have to create a docker swarm to get solr cloud to work properly in docker?

**Comment by makuk66** [comment] 2019-07-30 16:04
> your docker-compose.yml

Which? This one https://github.com/docker-solr/docker-solr#single-server-with-docker-compose? That is "to run a single standalone server".

Or this one https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml?

**Comment by oldmanoldson** [comment] 2019-07-30 16:06
The second link with the 3 solr nodes and zookeeper

**Comment by makuk66** [comment] 2019-07-31 09:09
Thanks -- that gives me enough to go on. I think this problem is caused by an incompatible config change in ZooKeeper 3.5. I've updated https://github.com/docker-solr/docker-solr-examples/blob/master/docker-compose/docker-compose.yml to specify `:3.4`. With 3.5, it looks like you need https://raw.githubusercontent.com/docker-solr/docker-solr-examples/037fcedc5c2e99ce6dee16fff92eb91ed1a216bc/docker-compose/docker-compose.yml (from https://github.com/docker-solr/docker-solr-examples/pull/2).
Could you please try those out?

**Comment by oldmanoldson** [comment] 2019-08-01 17:11
That seemed to work.  Thanks!

**Comment by makuk66** [comment] 2019-08-01 17:24
OK coo, thanksl. If you get a chance to try the other one too that'd be great.

**Comment by qeepcologne** [comment] 2019-08-02 07:32
solr < 8.2 is not compatible with zookeeper 3.5.x, current release 8.2 should run with 3.5.5.

**Comment by makuk66** [comment] 2019-08-02 07:48
Thanks, that's good to know; I've updated the PR accordingly.

**Comment by qeepcologne** [comment] 2019-08-16 07:56
I tried zk 3.5.5 with solr 8.2 and it's working, but there is a bug in solr: https://lucene.472066.n3.nabble.com/Solr-8-2-0-having-issue-with-ZooKeeper-3-5-5-td4445527.html fixed for 8.3 parsing the result causing the ZK status could not be displayed in solr webinterface unter cloud.

**Comment by makuk66** [comment] 2019-08-16 08:45
Thanks for the info. It probably makes sense to wait for 8.3 then

**Closed** 2019-11-12 11:39 UTC
Labels: question
